<?php
$page_title = $page_title ?? 'International Visions LLC | Maryland Freight, Box Truck & Logistics';
$page_description = $page_description ?? 'International Visions LLC is a family-owned Maryland freight company hauling general freight with dependable communication, professional scheduling, and coast-to-coast logistics support.';
$active = $active ?? '';
$base_url = $base_url ?? '';
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title><?= htmlspecialchars($page_title) ?></title><meta name="description" content="<?= htmlspecialchars($page_description) ?>"><meta name="robots" content="index,follow"><meta name="theme-color" content="#071019">
<link rel="canonical" href="<?= htmlspecialchars($base_url) ?><?= basename($_SERVER['PHP_SELF']) ?>">
<meta property="og:title" content="<?= htmlspecialchars($page_title) ?>"><meta property="og:description" content="<?= htmlspecialchars($page_description) ?>"><meta property="og:type" content="website"><meta property="og:image" content="assets/hero-truck.jpg"><meta name="twitter:card" content="summary_large_image">
<link rel="icon" href="favicon.ico"><link rel="apple-touch-icon" href="apple-touch-icon.png"><link rel="manifest" href="site.webmanifest">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&family=Space+Grotesk:wght@500;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"><link rel="stylesheet" href="style.css">
<script async src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXXXX"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('js',new Date());gtag('config','G-XXXXXXXXXX');</script>
<script type="application/ld+json">{"@context":"https://schema.org","@type":"LocalBusiness","name":"International Visions LLC","email":"trucking@internationalvisionsllc.org","slogan":"The Heartbeat of Shipping","url":"<?= htmlspecialchars($base_url) ?>","areaServed":["Maryland","Baltimore","Washington DC","Mid-Atlantic","Denver","United States"],"description":"Family-owned freight carrier providing general freight hauling, box truck service, regional freight and nationwide logistics support."}</script>
</head><body><header class="topbar"><div class="container topbar-inner"><a class="brand" href="index.php" aria-label="International Visions LLC home"><img src="assets/logo.svg" alt="International Visions LLC logo"></a><nav class="nav nav-icons" aria-label="Main navigation"><a class="<?= $active==='home'?'active':'' ?>" href="index.php"><i class="fa-solid fa-house"></i> Home</a><span class="nav-sep"></span><a class="<?= $active==='services'?'active':'' ?>" href="services.php"><i class="fa-solid fa-truck-ramp-box"></i> Services</a><span class="nav-sep"></span><a class="<?= $active==='coverage'?'active':'' ?>" href="coverage.php"><i class="fa-solid fa-map-location-dot"></i> Coverage</a><span class="nav-sep"></span><a class="<?= $active==='about'?'active':'' ?>" href="about.php"><i class="fa-solid fa-heart-pulse"></i> About</a><span class="nav-sep"></span><a class="<?= $active==='support'?'active':'' ?>" href="support.php"><i class="fa-solid fa-circle-question"></i> Contact</a></nav><a class="pulse-nav-btn recruit" href="recruiting.php"><span></span><i class="fa-solid fa-id-card"></i> Recruiting Now</a><a class="pulse-nav-btn quote" href="contact.php#quote-form"><span></span><i class="fa-solid fa-comments"></i> Request Quote</a><button class="menu-toggle" aria-label="Open menu"><i class="fa-solid fa-bars"></i></button></div></header><div class="mobile-menu"><a href="index.php"><i class="fa-solid fa-house"></i> Home</a><a href="services.php"><i class="fa-solid fa-truck-ramp-box"></i> Services</a><a href="coverage.php"><i class="fa-solid fa-map-location-dot"></i> Coverage</a><a href="about.php"><i class="fa-solid fa-heart-pulse"></i> About</a><a href="support.php"><i class="fa-solid fa-circle-question"></i> Contact</a><a href="recruiting.php"><i class="fa-solid fa-id-card"></i> Recruiting Now</a><a href="contact.php#quote-form"><i class="fa-solid fa-comments"></i> Quote Form</a></div>
