<?php $page_title='Privacy Policy | International Visions LLC'; $page_description='Privacy Policy for International Visions LLC covering contact forms, quote requests, support inquiries and website communications.'; include 'inc/header.php'; ?>
<main><section class="page-hero"><div class="container animated in"><span class="eyebrow"><span class="dot"></span> Privacy Policy</span><h1>Privacy Policy.</h1><p class="lead">International Visions LLC respects the privacy of customers, shippers, brokers, drivers and website visitors.</p></div></section>
<section class="section"><div class="container legal panel animated">
<h2>Information we collect</h2><p>When you use our quote, contact or driver interest forms, we may collect your name, company, email address, telephone number, address, pickup and destination details, freight type, shipment notes, preferred dates and other information you choose to provide.</p>
<h2>How we use information</h2><p>We use submitted information to respond to inquiries, review freight requests, coordinate communication, support business operations, improve website performance and maintain records connected to legitimate company activity.</p>
<h2>Sharing information</h2><p>We do not sell personal information. Information may be shared with service providers, hosting providers, email systems, professional advisers, regulators or business partners when necessary to operate the company, respond to requests, comply with law or support freight coordination.</p>
<h2>Analytics and website data</h2><p>The website may use analytics tools, server logs and cookies to understand traffic, improve performance and monitor reliability. Analytics identifiers should be configured responsibly and reviewed regularly.</p>
<h2>Your choices</h2><p>You may contact International Visions LLC to ask about information you submitted, request correction, or ask that unnecessary contact information be removed where retention is not required for business, safety, compliance or legal purposes.</p>
<h2>Contact</h2><p>Questions about this policy can be sent through the <a href="support.php">general contact form</a> or by emailing support@internationalvisionsllc.org.</p>
</div></section></main><?php include 'inc/footer.php'; ?>