<?php
function clean($v){ return trim(filter_var($v ?? '', FILTER_SANITIZE_SPECIAL_CHARS)); }
$name=clean($_POST['name']??''); $company=clean($_POST['company']??''); $phone=clean($_POST['phone']??''); $email=filter_var($_POST['email']??'', FILTER_VALIDATE_EMAIL); $origin=clean($_POST['origin']??''); $destination=clean($_POST['destination']??''); $weight=clean($_POST['weight']??''); $dropoff=clean($_POST['dropoff_date']??''); $pickup=clean($_POST['pickup_date']??''); $freight=clean($_POST['freight_type']??''); $notes=clean($_POST['notes']??'');
if(!$name||!$phone||!$email||!$origin||!$destination){ http_response_code(400); echo 'Missing required fields. Please go back and complete the form.'; exit; }
$admin='internationalvisionsllc@gmail.com';
$subject='New IVLLC Freight Callback Request: '.$origin.' to '.$destination;
$routeBlock='\n<div style="background:#071019;border-radius:22px;padding:20px;margin:18px 0;color:#fff;font-family:Arial,sans-serif;border:1px solid #1d344c">\n  <div style="font-size:12px;letter-spacing:2px;text-transform:uppercase;color:#e0c174;font-weight:bold">The Heartbeat of Shipping</div>\n  <h2 style="margin:8px 0 14px;color:#fff">Freight Route Request</h2>\n  <div style="display:flex;align-items:center;gap:12px;flex-wrap:wrap">\n    <div style="background:#0f2234;border:1px solid #244864;border-radius:16px;padding:12px 14px;min-width:150px"><b style="color:#69d3ff">Journey Start</b><br>'.htmlspecialchars($origin).'</div>\n    <div style="height:4px;flex:1;min-width:80px;background:repeating-linear-gradient(90deg,#69d3ff 0 10px,transparent 10px 20px);position:relative"></div>\n    <div style="background:#10202f;border:2px solid #e0c174;border-radius:14px;padding:12px 20px;font-weight:bold;color:#e0c174">TRUCK | '.htmlspecialchars($weight ?: 'Weight TBC').'</div>\n    <div style="height:4px;flex:1;min-width:80px;background:repeating-linear-gradient(90deg,#e0c174 0 10px,transparent 10px 20px)"></div>\n    <div style="background:#0f2234;border:1px solid #244864;border-radius:16px;padding:12px 14px;min-width:150px"><b style="color:#e0c174">Destination</b><br>'.htmlspecialchars($destination).'</div>\n  </div>\n</div>';
$table='<table cellpadding="8" cellspacing="0" style="border-collapse:collapse;width:100%;font-family:Arial,sans-serif;color:#071019"><tr><td><b>Name</b></td><td>'.htmlspecialchars($name).'</td></tr><tr><td><b>Company</b></td><td>'.htmlspecialchars($company).'</td></tr><tr><td><b>Phone</b></td><td>'.htmlspecialchars($phone).'</td></tr><tr><td><b>Email</b></td><td>'.htmlspecialchars($email).'</td></tr><tr><td><b>Pickup</b></td><td>'.htmlspecialchars($origin).'</td></tr><tr><td><b>Destination</b></td><td>'.htmlspecialchars($destination).'</td></tr><tr><td><b>Weight</b></td><td>'.htmlspecialchars($weight).'</td></tr><tr><td><b>Pickup Date</b></td><td>'.htmlspecialchars($pickup).'</td></tr><tr><td><b>Preferred Drop-Off Date</b></td><td>'.htmlspecialchars($dropoff).'</td></tr><tr><td><b>Freight Type</b></td><td>'.htmlspecialchars($freight).'</td></tr><tr><td><b>Notes</b></td><td>'.nl2br(htmlspecialchars($notes)).'</td></tr></table>';
$adminBody='<div style="font-family:Arial,sans-serif;background:#f5f8fc;padding:22px"><h1 style="color:#071019">New Freight Callback Request</h1>'.$routeBlock.$table.'</div>';
$userBody='<div style="font-family:Arial,sans-serif;background:#f5f8fc;padding:22px"><h1 style="color:#071019">Thank you for contacting International Visions LLC</h1><p>Hi '.htmlspecialchars($name).',</p><p>Our team will review your shipment and call you back shortly at <b>'.htmlspecialchars($phone).'</b>.</p>'.$routeBlock.'<p style="color:#334">International Visions LLC<br>The Heartbeat of Shipping</p></div>';
$headers="MIME-Version: 1.0\r\nContent-type:text/html;charset=UTF-8\r\nFrom: International Visions LLC <trucking@internationalvisionsllc.org>\r\nReply-To: ".$email."\r\n";
mail($admin,$subject,$adminBody,$headers);
mail($email,'International Visions LLC received your freight request',$userBody,$headers);
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Request Sent | International Visions LLC</title><link rel="stylesheet" href="style.css"></head><body><main class="page-hero"><div class="container"><span class="eyebrow"><span class="dot"></span> Request sent</span><h1>Thank you.</h1><p class="lead">Your freight request has been sent. Our team will review the shipment and call you shortly at <?= htmlspecialchars($phone) ?>.</p><a class="btn btn-primary" href="index.php">Return Home</a></div></main></body></html>
